spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:quadrodb
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
oauth2:
  exchange:
    providers:
      google:
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}
        redirect-uri: 'http://localhost:3000'

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO