spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:quadrodb
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#TODO remove basic auth
auth-user:
  name: ${USER_NAME}
  password: ${USER_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs